02 - Web UI Template/CognitiveSearch.UI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using CognitiveSearch.UI.Configuration;
using CognitiveSearch.UI.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;

namespace CognitiveSearch.UI.Controllers
{
    public class AdminController : Controller
    {
        private readonly IFileProvider _fileProvider;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly AppConfig _appConfig;

        public AdminController(IFileProvider fileProvider, IWebHostEnvironment hostingEnvironment, AppConfig appConfig)
        {
            _fileProvider = fileProvider;
            _hostingEnvironment = hostingEnvironment;
            _appConfig = appConfig;
        }

        [HttpGet]
        public async Task<IActionResult> Customize()
        {
            var model = new CustomizeViewModel
            {
                NavBar = await ReadCssColorProperties("navbar")
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CustomizeNavBar()
        {
            var cssString = "";
            var hasLogo = Request.Form.Files.Any(file => !string.IsNullOrEmpty(file.FileName));

            if (hasLogo)
            {
                var file = Request.Form.Files[0];
                if (file.FileName.EndsWith(".png", StringComparison.InvariantCultureIgnoreCase))
                {
                    var fi = new FileInfo(file.FileName);

                    var webPath = _hostingEnvironment.WebRootPath;
                    var path = Path.Combine("", webPath + @"\images\logo.png");

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                }
                else
                {
                    ViewBag.Style = "alert-warning";
                    ViewBag.Message = $"Only .png file supported. Please choose a different file and try again.";

                    var m = new CustomizeViewModel
                    {
                        NavBar = await ReadCssColorProperties("navbar")
                    };
                    return View("Customize", m);
                }
            }

            var hasBgColor = Request.Form.Keys.Any(k => k == "navbar-bg");
            var bgColorHead = hasBgColor ? Request.Form["navbar-bg"].ToString() : "#ffffff";
            var bgColorFooter = hasBgColor ? Request.Form["navbar-bg"].ToString() : "#efefef";
            cssString += $".navbar-bg{{background-color:{bgColorHead}}}";
            cssString += $".footer-bg{{background-color:{bgColorFooter}}}";

            var hasTextColor = Request.Form.Keys.Any(k => k == "navbar-text");
            var textColor = hasTextColor ? Request.Form["navbar-text"].ToString() : "#4A4A4A";
            cssString += $".navbar-text-color{{color:{textColor}}}";

            await WriteCss("navbar", cssString);

            ViewBag.Message = $"Successfully updated the navigation bar.";

            var model = new CustomizeViewModel
            {
                NavBar = await ReadCssColorProperties("navbar")
            };
            return View("Customize", model);
        }

        private async Task WriteCss(string fileName, string fileContent)
        {
            var webPath = _hostingEnvironment.WebRootPath;
            var path = Path.Combine("", webPath + $"\\css\\{fileName}.css");

            await System.IO.File.WriteAllTextAsync(path, fileContent);
        }

        private async Task<string> ReadCssImageNameProperty(string fileName)
        {
            var webPath = _hostingEnvironment.WebRootPath;
            var path = Path.Combine("", webPath + $"\\css\\{fileName}.css");

            var fileText = await System.IO.File.ReadAllTextAsync(path);
            
            var nameStart = fileText.IndexOf("../images/") + "..images/".Length + 1;
            var nameEnd = fileText.IndexOf("');");
            var length = nameEnd - nameStart;

            var logoName = fileText.Substring(nameStart, length);

            return logoName;
        }

        private async Task<ColorSettings> ReadCssColorProperties(string section)
        {
            var colorSettings = new ColorSettings();
            var webPath = _hostingEnvironment.WebRootPath;
            var path = Path.Combine("", webPath + $"\\css\\{section}.css");

            var css = await System.IO.File.ReadAllTextAsync(path);
            var parts = css.Split($"{section}-", StringSplitOptions.RemoveEmptyEntries);
            var props = new Dictionary<string, string>();

            foreach (var part in parts)
            {
                var partClean = part.Substring(part.IndexOf("{") + 1).Replace("}.", "").Replace("}", "");
                var subParts = partClean.Split(":", StringSplitOptions.RemoveEmptyEntries);
                if (partClean.StartsWith("background-color:"))
                {
                    colorSettings.BackgroundColor = subParts[1];
                }
                if (partClean.StartsWith("color:"))
                {
                    colorSettings.TextColor = subParts[1];
                }
            }
            return colorSettings;
        }

        public async Task<IActionResult> DownloadCustomCss()
        {
            var webPath = _hostingEnvironment.WebRootPath;
            var path = Path.Combine("", webPath + @"\css\custom.css");

            var memory = new MemoryStream();
            using(var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, "text/css", "custom.css");
        }

        [HttpPost]
        public async Task<IActionResult> UploadCustomCss()
        {
            foreach (var file in Request.Form.Files)
            {
                if (file.Length > 0)
                {
                    var webPath = _hostingEnvironment.WebRootPath;
                    var path = Path.Combine("", webPath + @"\css\custom.css");

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                }
            }

            ViewBag.Message = $"Custom CSS file uploaded as to the web server successfully";

            return View("Customize");
        }

        [HttpGet]
        public IActionResult UploadData()
        {
            return View(_appConfig);
        }

        [HttpGet]
        public IActionResult Deploy()
        {
            return View();
        }

        [HttpGet]
        public IActionResult NotAvailable()
        {
            return View();
        }
    }
}

02 - Web UI Template/CognitiveSearch.UI/Controllers/AdvancedController.cs
using CognitiveSearch.UI.CognitiveSearchApi;
using CognitiveSearch.UI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;

namespace CognitiveSearch.UI.Controllers
{
    public class AdvancedController : Controller
    {
        private IConfiguration _configuration { get; set; }
        private CognitiveSearchApiClient _apiClient { get; set; }
        private string _configurationError { get; set; }

        public AdvancedController(IConfiguration configuration)
        {
            _configuration = configuration;
            InitializeApiClient();
        }

        private void InitializeApiClient()
        {
            try
            {
                _apiClient = new CognitiveSearchApiClient(_configuration);
            }
            catch (Exception e)
            {
                _configurationError = $"The application settings are possibly incorrect. The server responded with this message: " + e.Message.ToString();
            }
        }

        public IActionResult Synonyms()
        {
            var viewModel = new SynonymMapsViewModel
            {
                SynonymMapList = GetSynonymMapList()
            };

            return View(viewModel);
        }

        public IActionResult NewSynonymMap()
        {
            var synonymMap = new SynonymMap();

            return View("CreateSynonymMap", synonymMap);
        }

        public IActionResult CreateSynonymMap(SynonymMap synonymMap)
        {
            InitializeApiClient();

            //Get encryptionKey
            var keyVaultKeyName = _configuration.GetSection("keyVaultKeyName").Value;
            var keyVaultKeyVersion = _configuration.GetSection("keyVaultKeyVersion").Value;
            var keyVaultUri = _configuration.GetSection("keyVaultUri").Value;

            if(!string.IsNullOrEmpty(keyVaultKeyName) && !string.IsNullOrEmpty(keyVaultKeyVersion) && !string.IsNullOrEmpty(keyVaultUri))
            {
                synonymMap.encryptionKey = new EncryptionKey
                {
                    keyVaultKeyName = keyVaultKeyName != "" ? keyVaultKeyName : null,
                    keyVaultKeyVersion = keyVaultKeyVersion != "" ? keyVaultKeyVersion : null,
                    keyVaultUri = keyVaultUri != "" ? keyVaultUri : null,
                };
            }
            

            var searchApiResponse = _apiClient.CreateSynonymMap(synonymMap).Result;

            if (searchApiResponse.IsSuccessStatusCode)
            {
                return RedirectToAction("Synonyms");
            }
            else
            {
                ErrorViewModel error = new ErrorViewModel
                {
                    ErrorMessage = searchApiResponse.Content
                };

                return RedirectToAction("SearchApiResponseError", "Home",  error);
            }

        }

        public IActionResult MakeActiveSynonymMap(string name)
        {
            InitializeApiClient();

            var searchApiResponse = _apiClient.UpdateIndexSynonymMap(name, false).Result;

            if (searchApiResponse.IsSuccessStatusCode)
            {
                return RedirectToAction("Synonyms");
            }
            else
            {
                ErrorViewModel error = new ErrorViewModel
                {
                    ErrorMessage = searchApiResponse.Content
                };

                return RedirectToAction("SearchApiResponseError", "Home", error);
            }
        }

        public IActionResult EditSynonymMap(string name)
        {
            InitializeApiClient();

            var synonymMap = _apiClient.GetSynonymMap(name).Result;

            return View(synonymMap);
        }

        public IActionResult DeleteSynonymMap(string name)
        {
            InitializeApiClient();

            var searchApiResponse = _apiClient.DeleteSynonymMap(name).Result;


            if (searchApiResponse.IsSuccessStatusCode)
            {
                return RedirectToAction("Synonyms");
            }
            else
            {
                ErrorViewModel error = new ErrorViewModel
                {
                    ErrorMessage = searchApiResponse.Content
                };

                return RedirectToAction("SearchApiResponseError", "Home", error);
            }
        }

        public IActionResult UpdateSynonymMap(SynonymMap synonymMap)
        {
            InitializeApiClient();

            var searchApiResponse = _apiClient.UpdateSynonymMap(synonymMap).Result;

            if (searchApiResponse.IsSuccessStatusCode)
            {
                return RedirectToAction("Synonyms");
            }
            else
            {
                ErrorViewModel error = new ErrorViewModel
                {
                    ErrorMessage = searchApiResponse.Content
                };

                return RedirectToAction("SearchApiResponseError", "Home", error);
            }

        }

        public SynonymMapList GetSynonymMapList()
        {
            InitializeApiClient();

            return _apiClient.GetSynonymMaps().Result;           
        }
    }
}

02 - Web UI Template/CognitiveSearch.UI/Controllers/CaseManagementController.cs
using Microsoft.AspNetCore.Mvc;

namespace CognitiveSearch.UI.Controllers
{
    public class CaseManagementController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

02 - Web UI Template/CognitiveSearch.UI/Views/Shared/_Footer.cshtml
@using CognitiveSearch.UI.Configuration
@inject OrganizationConfig OrgConfig

	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
<div>
	<footer class="main-footer navbar-bg">
		<div class="content">
			<span class="copyright navbar-text-color">&copy; @DateTime.Now.Year - @OrgConfig.Name</span>
		</div>
	</footer>
</div>

02 - Web UI Template/CognitiveSearch.UI/Views/Shared/_Header.cshtml
@using CognitiveSearch.UI.Configuration
@inject AppConfig AppConfig

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-bg">
    <div class="container-fluid">
        <div class="content">
            <div class="navbar-header">
                <a class="navbar-brand-logo" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo.png" height="35" id="navbar-img" alt="@AppConfig.Organization.Name logo" title="@AppConfig.Organization.Name logo" class="logo-container logo-sgv" asp-append-version="true" />
                </a>
            </div>
            @if (AppConfig.Customizable)
            {
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="navbar-text navbar-text-color" asp-area="" asp-controller="Home" asp-action="Search">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="navbar-text navbar-text-color" asp-area="" asp-controller="CaseManagement" asp-action="Index">Case Management</a>
                        </li>
                        <li class="nav-item">
                            <a id="customize-page" class="navbar-text navbar-text-color" asp-area="" asp-controller="Admin" asp-action="Customize">Customize</a>
                        </li>
                        <li class="nav-item">
                            <a id="upload-data-page" class="navbar-text navbar-text-color" asp-area="" asp-controller="Admin" asp-action="UploadData">Upload Files</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="navbar-text navbar-text-color dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Advanced</span> <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Advanced" asp-action="Synonyms">Synonyms</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            }
        </div>

    </div>
</nav>

@if (!string.IsNullOrWhiteSpace(ViewBag.Message))
{
    @if (!string.IsNullOrWhiteSpace(ViewBag.Style))
    {
        <div class="alert @ViewBag.Style  mb-2 mt-5 mr-5 ml-5">@ViewBag.Message</div>
    }
    else
    {
        <div class="alert alert-info  mb-2 mt-5 mr-5 ml-5">@ViewBag.Message</div>
    }
}

02 - Web UI Template/CognitiveSearch.UI/Views/Shared/_Layout.cshtml
<!-- Copyright (c) Microsoft Corporation. All rights reserved.
     Licensed under the MIT License. -->

@using CognitiveSearch.UI.Configuration
@inject AppConfig AppConfig

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/css/fabric.components.min.css" />
    <link rel="stylesheet" href="~/lib/fabric-ui/fabric.css" />
    <link rel="stylesheet" href="~/lib/fabric-ui/fabric-9.4.0.scoped.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-theme.min.css" />

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.css" type="text/css">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/navbar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/colors.css" />

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>

    <script src="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/js/fabric.min.js"></script>
    <script src="https://d3js.org/d3.v4.min.js"></script>
    <script src="https://d3js.org/d3-selection-multi.v1.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
    
    <script src="https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.js"></script>
</head>
<body>
    @await Html.PartialAsync("_Header")

    <div class="container-fluid">
        @RenderBody()
    </div>

    @await Html.PartialAsync("_Footer")

    <script type="text/javascript">
        // Change JQueryUI plugin names to fix name collision with Bootstrap.
        $.widget.bridge('uitooltip', $.ui.tooltip);
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    <script src="~/js/tags.js"></script>
    <script src="~/js/details.js"></script>
    <script src="~/js/appInsights.js"></script>
    <script src="~/js/results.js"></script>
    <script src="~/js/facets.js"></script>
    <script src="~/js/search.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/entityMap.js"></script>
    <script src="~/js/PolygonDrawingTool.js"></script>

    <script>
        $(function () {
            $('.advancedAutoComplete').autocomplete({
                source: "/home/suggest",
                minLength: 2,
                select: function (event, ui) {
                    Search();
                }
            });
		})

        customizable = '@AppConfig.Customizable';
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>